spring:
  application:
    name: graphql-service
  profiles:
    active: dev
  datasource:
    url:
      jdbc:
        h2:
          mem:
            custome-test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        default_schema: null
      
server:
  port: 8080
  context-path: /
