server:
  port: 8081
  server-context: /
  ssl:
    enabled: true
    key-store: "src/main/resources/server2-keystore.jks"
    key-store-password: password2
    key-store-type: PKCS12
    client-auth: want
    trust:
      enabled: true
      file: "src/main/resources/server-keystore.jks"
      password: password
     
spring:
  application:
    name: ssl-server-service
